export const REGIONS = [
  "All Regions",
  "Addis Ababa",
  "Amhara",
  "Tigray",
  "Afar",
  "Oromia",
  "Sidama",
  "South Ethiopia",
  "Harari",
];

export const CATEGORIES = [
  "All",
  "Historical",
  "Nature & Wildlife",
  "Adventure",
  "Cultural",
  "Religious",
];

export const STARTING_LOCATIONS = [
  { id: "addis-ababa", name: "Addis Ababa (Capital)", lat: 9.0320, lng: 38.7469, isDefault: true },
  { id: "bahir-dar", name: "Bahir Dar", lat: 11.5936, lng: 37.3908 },
  { id: "gondar", name: "Gondar", lat: 12.6030, lng: 37.4521 },
  { id: "hawassa", name: "Hawassa", lat: 7.0504, lng: 38.4763 },
  { id: "dire-dawa", name: "Dire Dawa", lat: 9.5931, lng: 41.8661 },
];

export const DESTINATIONS = [
  {
    id: "lalibela",
    slug: "lalibela",
    name: "Lalibela",
    region: "Amhara",
    category: "Religious",
    rating: 4.9,
    reviewsCount: 142,
    price: 180, // USD
    level: "Easy",
    lat: 12.0316,
    lng: 39.0473,
    tag: "UNESCO",
    shortDesc: "Eleven medieval monolithic rock-hewn churches carved downward into red volcanic rock, active for over 800 years.",
    desc: "Eleven medieval rock-hewn churches carved downward into volcanic rock, still an active pilgrimage site.",
    description: "Known as the New Jerusalem, Lalibela is a high-mountain town in northern Ethiopia famous for its 11 monolithic and semi-monolithic churches carved directly out of solid volcanic basalt in the 12th and 13th centuries under King Lalibela. The cross-shaped Church of Saint George (Bete Giyorgis) is the most iconic architectural marvel, connected by an intricate subterranean network of trenches and ceremonial tunnels.",
    imageUrl: "https://images.unsplash.com/photo-1578922864835-e9b4661a5b8a?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1578922864835-e9b4661a5b8a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1609137144822-4a005ee56a64?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Visit the iconic cross-shaped Bete Giyorgis (Church of Saint George)",
      "Explore the Northern & Eastern Church Clusters linked by ancient tunnels",
      "Hike or ride mule to the high-altitude Asheton Maryam Monastery",
      "Experience early morning Orthodox choral chants and Timkat celebrations",
      "Sample Tej (honey wine) and traditional fasting food in local casas",
    ],
    bestSeason: "October to March",
    durationDays: "2 – 3 Days",
    distanceFromAddis: 680,
    driveTimeFromAddis: 11.5,
    flightAvailable: true,
    costs: {
      transportCost: 3500, // ETB
      accommodationCost: 3200, // ETB / night
      foodCost: 900, // ETB / day
      activityCost: 2500, // ETB (Entrance & Guide)
    },
  },
  {
    id: "simien-mountains",
    slug: "simien-mountains",
    name: "Simien Mountains",
    region: "Amhara",
    category: "Nature & Wildlife",
    rating: 4.8,
    reviewsCount: 118,
    price: 240,
    level: "Challenging",
    lat: 13.1833,
    lng: 38.0500,
    tag: "Trekking",
    shortDesc: "Spectacular jagged escarpments, dramatic 1,500m drops, and the native kingdom of the Gelada baboon and Walia ibex.",
    desc: "Jagged escarpments, roaming gelada monkeys, and trekking routes above 4,000m.",
    description: "The Simien Mountains National Park is a UNESCO World Heritage site known as 'The Chessboard of the Gods'. Massive erosion over millions of years has created one of the most spectacular landscapes in the world, with jagged mountain peaks, deep valleys, and precipices dropping some 1,500m. It is the sole refuge for the endemic Walia ibex, Ethiopian wolf, and thousands of gentle vegetarian Gelada baboons.",
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Trek along the escarpment from Sankaber to Geech camp",
      "Sit among friendly troops of bleeding-heart Gelada baboons",
      "Stand before the cascading Jinbar Waterfall into the abyss",
      "Summit Ras Dejen (4,550m), the highest peak in Ethiopia",
      "Camp under pristine star-filled African highland skies",
    ],
    bestSeason: "October to April",
    durationDays: "3 – 5 Days",
    distanceFromAddis: 840,
    driveTimeFromAddis: 14,
    flightAvailable: true,
    costs: {
      transportCost: 4800,
      accommodationCost: 2800,
      foodCost: 1100,
      activityCost: 3500,
    },
  },
  {
    id: "danakil-depression",
    slug: "danakil-depression",
    name: "Danakil Depression",
    region: "Afar",
    category: "Adventure",
    rating: 4.7,
    reviewsCount: 95,
    price: 320,
    level: "Extreme",
    lat: 14.2417,
    lng: 40.3000,
    tag: "Extreme",
    shortDesc: "Vibrant neon-yellow sulphur springs, immense salt pans, and the bubbling glowing lava lake of Erta Ale volcano.",
    desc: "Sulphur springs, salt flats, and an active lava lake — one of the hottest, lowest places on Earth.",
    description: "Located at the junction of three tectonic plates in the Afar Triangle, the Danakil Depression is one of the lowest (-125m below sea level) and hottest places on Earth. The otherworldly neon-green and yellow hydrothermal vents of Dallol, boundless crystalline salt crusts of Lake Karum, and the active caldera of Erta Ale volcano offer an expedition unmatched anywhere on the planet.",
    imageUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Walk among the steaming neon-yellow and turquoise chimneys of Dallol",
      "Watch Afar camel caravans transport hand-cut salt slabs across Lake Assal",
      "Trek to the rim of Erta Ale and gaze into the glowing molten lava lake",
      "Float in the ultra-saline turquoise waters of Lake Gaet'ale",
      "Experience night under the stars in traditional Afar woven huts",
    ],
    bestSeason: "November to February",
    durationDays: "3 – 4 Days",
    distanceFromAddis: 790,
    driveTimeFromAddis: 13,
    flightAvailable: true,
    costs: {
      transportCost: 6500,
      accommodationCost: 3500,
      foodCost: 1400,
      activityCost: 4800,
    },
  },
  {
    id: "gondar",
    slug: "gondar",
    name: "Gondar",
    region: "Amhara",
    category: "Historical",
    rating: 4.6,
    reviewsCount: 88,
    price: 140,
    level: "Easy",
    lat: 12.6030,
    lng: 37.4521,
    tag: "UNESCO",
    shortDesc: "The 17th-century 'Camelot of Africa' featuring regal fortified castles and the angel-ceilinged Debre Berhan Selassie.",
    desc: "Royal castles and enclosures earning it the nickname 'Africa's Camelot'.",
    description: "Founded by Emperor Fasilides in 1636, Gondar served as Ethiopia's royal capital for over two centuries. The Fasil Ghebbi royal compound boasts fairytale stone castles blending Portuguese, Moorish, and Aksumite architectural styles. Nearby, the famous Debre Berhan Selassie church is decorated with iconic painted ceiling angels looking down upon worshippers.",
    imageUrl: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Tour the massive stone castles of Fasil Ghebbi royal enclosure",
      "Admire the iconic 80 angel faces ceiling at Debre Berhan Selassie",
      "Visit Fasilides' Bath, center of the annual Timkat epiphany reenactment",
      "Explore the ruins of Kuskuam Palace and Empress Mentewab's residence",
    ],
    bestSeason: "September to May",
    durationDays: "1 – 2 Days",
    distanceFromAddis: 740,
    driveTimeFromAddis: 12,
    flightAvailable: true,
    costs: {
      transportCost: 3200,
      accommodationCost: 2600,
      foodCost: 850,
      activityCost: 1800,
    },
  },
  {
    id: "bahir-dar",
    slug: "bahir-dar",
    name: "Bahir Dar",
    region: "Amhara",
    category: "Nature & Wildlife",
    rating: 4.5,
    reviewsCount: 110,
    price: 130,
    level: "Easy",
    lat: 11.5936,
    lng: 37.3908,
    tag: "Nature",
    shortDesc: "Palm-fringed shores of Lake Tana, ancient island monasteries, and the magnificent Blue Nile Falls (Tis Issat).",
    desc: "Island monasteries on Ethiopia's largest lake and the thundering source of the Blue Nile.",
    description: "Bahir Dar is a vibrant lakeside city with wide palm-lined boulevards on the southern shore of Lake Tana, the largest lake in Ethiopia and source of the Blue Nile. Boat tours take visitors to medieval monasteries like Ura Kidane Mehret adorned with vibrant centuries-old religious paintings, followed by an excursion to Tis Issat (Smoking Water) falls.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Take a boat across Lake Tana to Zege Peninsula monasteries",
      "Hike to the viewpoint of Tis Issat (Blue Nile Falls)",
      "Watch local fishermen glide on traditional papyrus tankwa boats",
      "Stroll along the lakeside promenades at sunset with fresh tilapia",
    ],
    bestSeason: "September to April",
    durationDays: "2 Days",
    distanceFromAddis: 565,
    driveTimeFromAddis: 9.5,
    flightAvailable: true,
    costs: {
      transportCost: 2800,
      accommodationCost: 2400,
      foodCost: 800,
      activityCost: 2000,
    },
  },
  {
    id: "axum",
    slug: "axum",
    name: "Axum",
    region: "Tigray",
    category: "Historical",
    rating: 4.6,
    reviewsCount: 74,
    price: 150,
    level: "Easy",
    lat: 14.1213,
    lng: 38.7269,
    tag: "UNESCO",
    shortDesc: "The ancient seat of the Aksumite Empire, towering granite stelae, and sanctuary of the Ark of the Covenant.",
    desc: "Ancient obelisks and ruins of the Kingdom of Aksum, said to house the Ark of the Covenant.",
    description: "The birthplace of Ethiopian civilization and one of the great naval trade empires of the ancient world. Axum is renowned for its colossal monolithic granite obelisks, the Queen of Sheba's bath, ancient royal tombs with Ge'ez inscriptions, and the Church of Our Lady Mary of Zion, where the sacred Ark of the Covenant is guarded.",
    imageUrl: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Stand beneath the 24-meter Great Stelae in the Northern Stelae Field",
      "Visit the Chapel of the Tablet at St. Mary of Zion Church",
      "Explore the archaeological ruins of Dungur (Queen of Sheba's Palace)",
      "Descend into the underground royal tombs of King Kaleb and Gebre Meskel",
    ],
    bestSeason: "October to April",
    durationDays: "1 – 2 Days",
    distanceFromAddis: 1020,
    driveTimeFromAddis: 16,
    flightAvailable: true,
    costs: {
      transportCost: 4000,
      accommodationCost: 2500,
      foodCost: 850,
      activityCost: 1900,
    },
  },
  {
    id: "harar",
    slug: "harar",
    name: "Harar Jugol",
    region: "Harari",
    category: "Cultural",
    rating: 4.5,
    reviewsCount: 82,
    price: 130,
    level: "Easy",
    lat: 9.3131,
    lng: 42.1183,
    tag: "UNESCO",
    shortDesc: "The 4th holiest city in Islam, with 82 historic mosques, vibrant painted alleyways, and the nightly hyena feeding ritual.",
    desc: "A walled Islamic city of 82 mosques, colourful alleyways, and the famous hyena feeding.",
    description: "Surrounded by a 16th-century fortified wall with five historic gates, Harar Jugol is a maze of 368 narrow alleys lined with traditional Harari townhouse museums, spice markets, and coffee houses. At dusk, the famous 'Hyena Men' of Harar call wild spotted hyenas by name to feed them raw meat from hand and mouth in an extraordinary tradition.",
    imageUrl: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Witness the thrilling nightly wild hyena feeding ceremony outside the walls",
      "Wander the colorful pastel alleys and traditional Harari cultural houses (Gegar)",
      "Visit the Arthur Rimbaud Cultural Center & museum",
      "Savor authentic world-renowned Harar single-origin coffee and freshly ground spices",
    ],
    bestSeason: "Year-round (Best Oct–Mar)",
    durationDays: "2 Days",
    distanceFromAddis: 525,
    driveTimeFromAddis: 8.5,
    flightAvailable: true,
    costs: {
      transportCost: 3000,
      accommodationCost: 2200,
      foodCost: 800,
      activityCost: 1500,
    },
  },
  {
    id: "bale-mountains",
    slug: "bale-mountains",
    name: "Bale Mountains",
    region: "Oromia",
    category: "Nature & Wildlife",
    rating: 4.7,
    reviewsCount: 68,
    price: 210,
    level: "Moderate",
    lat: 6.8833,
    lng: 39.7500,
    tag: "Wildlife",
    shortDesc: "Afro-alpine Sanetti Plateau, dense Harenna Cloud Forest, and the world's highest concentration of endangered Ethiopian wolves.",
    desc: "Afro-alpine highlands and the best chance on Earth to see the rare Ethiopian wolf.",
    description: "Bale Mountains National Park protects the largest area of Afro-alpine habitat on the African continent. Across the 4,000m Sanetti Plateau, giant lobelias dot the misty terrain where the striking red-coated Ethiopian wolf hunts giant mole-rats. To the south, the plateau plunges into the mystical, lichen-draped Harenna tropical rainforest.",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Spot the rare Ethiopian Wolf hunting on the windswept Sanetti Plateau",
      "Drive Africa's highest all-weather road across the Afro-alpine plateau",
      "Hike beneath moss-draped canopy trees in the Harenna Cloud Forest",
      "Horseback trek through Gaysay Grasslands to see Mountain Nyala and Menelik's bushbuck",
    ],
    bestSeason: "November to April",
    durationDays: "3 Days",
    distanceFromAddis: 400,
    driveTimeFromAddis: 7,
    flightAvailable: false,
    costs: {
      transportCost: 4200,
      accommodationCost: 3000,
      foodCost: 950,
      activityCost: 2800,
    },
  },
  {
    id: "omo-valley",
    slug: "omo-valley",
    name: "Omo Valley",
    region: "South Ethiopia",
    category: "Cultural",
    rating: 4.5,
    reviewsCount: 76,
    price: 260,
    level: "Moderate",
    lat: 5.9333,
    lng: 36.5667,
    tag: "Cultural",
    shortDesc: "A UNESCO living cultural tapestry home to the Mursi, Hamer, Karo, and Dassanech tribes with rich body ornamentation and ceremonies.",
    desc: "Home to more than a dozen distinct indigenous communities and centuries-old traditions.",
    description: "The Lower Omo Valley is one of the most culturally diverse regions in Africa, inhabited by over a dozen distinct tribal groups who have preserved their ancestral lifestyle for centuries. Known for the lip-plates of the Mursi, body art of the Karo, and the famous Bull Jumping rites of passage among the Hamer.",
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Visit traditional Mursi and Hamer homestead villages with local cultural guides",
      "Attend an authentic Hamer Bull Jumping initiation ceremony and Evangadi dance",
      "Cross the Omo River in a wooden dugout canoe to visit Dassanech communities",
      "Explore the bustling tribal market days at Dimeka, Turmi, and Key Afer",
    ],
    bestSeason: "June to September & December to March",
    durationDays: "4 – 6 Days",
    distanceFromAddis: 750,
    driveTimeFromAddis: 12.5,
    flightAvailable: true,
    costs: {
      transportCost: 5500,
      accommodationCost: 3200,
      foodCost: 1100,
      activityCost: 4000,
    },
  },
  {
    id: "hawassa",
    slug: "hawassa",
    name: "Hawassa",
    region: "Sidama",
    category: "Nature & Wildlife",
    rating: 4.6,
    reviewsCount: 92,
    price: 110,
    level: "Easy",
    lat: 7.0504,
    lng: 38.4763,
    tag: "Lakeside",
    shortDesc: "Serene Rift Valley lake city, vibrant morning fish market, colobus monkeys, and relaxing lakeside eco-resorts.",
    desc: "Vibrant Rift Valley city with lakeside promenades, famous fish market and birdlife.",
    description: "Nestled in the Main Ethiopian Rift Valley, Hawassa is a peaceful lakeside resort city known for its beautiful shoreline promenade, relaxing climate, and lush greenery. The famous morning fish market (Amora Gedel) attracts fishermen selling fresh grilled tilapia alongside giant marabou storks, pelicans, and friendly black-and-white colobus monkeys.",
    imageUrl: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Experience the bustling Amora Gedel morning fish market and try fresh fried fish",
      "Boat ride on Lake Hawassa to spot pods of hippos and aquatic birds",
      "Stroll through lakeside parks inhabited by troops of Colobus monkeys",
      "Hike or bike up Mount Tabor for panoramic city and lake sunset views",
    ],
    bestSeason: "Year-round",
    durationDays: "1 – 2 Days",
    distanceFromAddis: 275,
    driveTimeFromAddis: 4.5,
    flightAvailable: true,
    costs: {
      transportCost: 2000,
      accommodationCost: 2200,
      foodCost: 750,
      activityCost: 1200,
    },
  },
  {
    id: "arba-minch",
    slug: "arba-minch",
    name: "Arba Minch & Nechisar",
    region: "South Ethiopia",
    category: "Nature & Wildlife",
    rating: 4.6,
    reviewsCount: 78,
    price: 175,
    level: "Moderate",
    lat: 6.0333,
    lng: 37.5500,
    tag: "Safari",
    shortDesc: "The 'Bridge of God' dividing Lake Chamo and Abaya, huge Nile crocodiles, Nechisar National Park plains, and Dorze bamboo huts.",
    desc: "Forty springs, Lake Chamo's giant crocodile market, and Dorze elephant-shaped houses.",
    description: "Arba Minch ('Forty Springs') is named for its bubbling groundwater springs emerging from a lush groundwater forest. Overlooking the narrow land bridge separating the reddish Lake Abaya from the blue Lake Chamo, boat trips on Lake Chamo get you within feet of some of Africa's largest Nile crocodiles and hippos. Up in the nearby Guge Mountains, the Dorze people weave organic cotton and craft majestic beehive-shaped houses from bamboo.",
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Boat safari on Lake Chamo to see the massive Nile crocodile 'market' and hippos",
      "Visit Chencha highland village to see Dorze bamboo architecture and taste Kocho bread",
      "Explore the 40 natural springs and natural springs forest trail",
      "Safari across the grassy savannah plains of Nechisar National Park",
    ],
    bestSeason: "October to April",
    durationDays: "2 – 3 Days",
    distanceFromAddis: 450,
    driveTimeFromAddis: 7.5,
    flightAvailable: true,
    costs: {
      transportCost: 3400,
      accommodationCost: 2600,
      foodCost: 850,
      activityCost: 2200,
    },
  },
  {
    id: "addis-ababa",
    slug: "addis-ababa",
    name: "Addis Ababa",
    region: "Addis Ababa",
    category: "Cultural",
    rating: 4.7,
    reviewsCount: 165,
    price: 95,
    level: "Easy",
    lat: 9.0320,
    lng: 38.7469,
    tag: "Capital",
    shortDesc: "The diplomatic capital of Africa, Lucy (Dinknesh) at the National Museum, Entoto panoramic views, and Africa's largest open-air market.",
    desc: "Ethiopia's vibrant capital, home to 3.2-million-year-old Lucy, Merkato, and Entoto Park.",
    description: "Addis Ababa ('New Flower') is Ethiopia's bustling capital and diplomatic headquarters of the African Union. Perched at 2,355 meters at the base of Mount Entoto, the city blends ancient heritage with a thriving modern art and culinary scene. Highlights include the National Museum housing the cast of Lucy, the sprawling open-air Merkato market, Holy Trinity Cathedral, and Unity Park inside the historic Grand Palace.",
    imageUrl: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1578922864835-e9b4661a5b8a?auto=format&fit=crop&w=800&q=80",
    ],
    thingsToDo: [
      "Meet 3.2-million-year-old hominid fossil Lucy (Dinknesh) at the National Museum",
      "Enjoy panoramic sunset views of the metropolis from Mount Entoto Park",
      "Explore the vast Merkato, the largest open-air marketplace in Africa",
      "Tour Unity Park & Emperor Menelik II's Palace within the Prime Minister compound",
      "Sip world-class freshly roasted Yirgacheffe coffee in traditional Jebena ceremonies",
    ],
    bestSeason: "Year-round",
    durationDays: "1 – 2 Days",
    distanceFromAddis: 0,
    driveTimeFromAddis: 0,
    flightAvailable: true,
    costs: {
      transportCost: 1200,
      accommodationCost: 3500,
      foodCost: 1000,
      activityCost: 1500,
    },
  },
];

export const TESTIMONIALS = [
  {
    name: "Sara M.",
    origin: "Netherlands",
    text: "Watching sunrise over Lalibela's carved churches was unlike anything I had planned for — the trip planner made the logistics and cost estimations effortless.",
    rating: 5,
  },
  {
    name: "Daniel K.",
    origin: "USA",
    text: "The Danakil trek was intense and mesmerizing. The ETB currency converter and route breakdown gave us total clarity before we landed in Addis.",
    rating: 5,
  },
  {
    name: "Amara T.",
    origin: "Kenya",
    text: "Booking and organizing our Simien Mountains route was smooth and straightforward. EthioExplore captures the authentic spirit of Ethiopia.",
    rating: 5,
  },
  {
    name: "Johannes W.",
    origin: "Germany",
    text: "From the castles in Gondar to the hyenas in Harar, this platform is the best tool available for planning independent travel across Ethiopia.",
    rating: 5,
  },
];

export const STATS = [
  { n: "100+", l: "Destinations" },
  { n: "50+", l: "Experiences" },
  { n: "10K+", l: "Travelers" },
  { n: "4.8", l: "Average rating" },
];

export const ETB_RATE = 161; // Fallback exchange rate (1 USD ≈ 161 ETB)

export function findDestination(idOrSlug) {
  if (!idOrSlug) return null;
  const key = idOrSlug.toLowerCase().trim();
  return DESTINATIONS.find((d) => d.id === key || d.slug === key);
}
